export const POST_JOURNAL_REQUEST = "POST_JOURNAL_REQUEST";
export const POST_JOURNAL_SUCCESS = "POST_JOURNAL_SUCCESS";
export const POST_JOURNAL_FAILURE = "POST_JOURNAL_FAILURE";

export const GET_JOURNAL_REQUEST = "GET_JOURNAL_REQUEST";
export const GET_JOURNAL_SUCCESS = "GET_JOURNAL_SUCCESS";
export const GET_JOURNAL_FAILURE = "GET_JOURNAL_FAILURE";

export const GET_JOURNAL_REQUEST_BY_ID = "GET_JOURNAL_REQUEST_BY_ID";
export const GET_JOURNAL_SUCCESS_BY_ID = "GET_JOURNAL_SUCCESS_BY_ID";
export const GET_JOURNAL_FAILURE_BY_ID = "GET_JOURNAL_FAILURE_BY_ID";

export const UPDATE_JOURNAL_REQUEST = "UPDATE_JOURNAL_REQUEST";
export const UPDATE_JOURNAL_SUCCESS = "UPDATE_JOURNAL_SUCCESS";
export const UPDATE_JOURNAL_FAILURE = "UPDATE_JOURNAL_FAILURE";

export const DELETE_JOURNAL_REQUEST = "DELETE_JOURNAL_REQUEST";
export const DELETE_JOURNAL_SUCCESS = "DELETE_JOURNAL_SUCCESS";
export const DELETE_JOURNAL_FAILURE = "DELETE_JOURNAL_FAILURE";