module.exports = {
  INV_CNTR_ID: 'Invalid Center Id',
  INV_HORSE_ID: 'Invalid Horse Id',
  INV_SALE_ID: 'Invalid Sale Id',
  INV_GENDER_ID: 'Invalid Gender Id',
  INV_COLOR_ID: 'Invalid Color Id',
  INV_DISCIPLINE_ID: 'Invalid Discipline Id',
  INV_BREED_ID: 'Invalid Breed Id',
  INV_OWNER_ID: 'Invalid Owner Id',
  INV_RACE_ID: 'Invalid Race Id',
  INV_USER_ID: 'Invalid User Id',
  INV_ROLE_ID: 'Invalid Role Id',
  INV_CNTR_NAME: 'Invalid Center Name',
  INV_OWNER_NAME: 'Invalid Owner Name',
  INV_DESC: 'Invalid Description',
  INV_EMAIL: 'Invalid Email',
  INV_EXP: 'Invalid Experience',
  INV_ADDR: 'Invalid Address',
  INV_URL: 'Invalid Website URL',
  INV_WORKING_HRS: 'Invalid Working Hours',
  INV_CONTACT_INFO: 'Invalid Contact Information',
  INV_USER_NAME: 'Invalid User name',
  INV_SUBJECT: 'Either Subject is not a string or is too short',
  INV_MESSAGE: 'Either Message is not a string or is too short',
  INV_PRICE: 'Invalid Price',
  INV_HORSE_NAME: 'Invalid Horse Name',
  INV_SHOW_NAME: 'Invalid Horse Showname',
  INV_MICROCHIP: 'Invalid Microchip Number',
  INV_HORSE_WEIGHT: 'Invalid Horse Weight',
  INV_HORSE_HEIGHT: 'Invalid Horse Height',
  INV_HORSE_BDATE: 'Invalid Birthdate',
  INV_HORSE_FNAME: 'Invalid Father Name',
  INV_HORSE_MNAME: 'Invalid Mother Name',
  INV_RACE_LENGTH: 'Invalid Race Length',
  INV_AGE_CRITERIA: 'Invalid Horse Age Criteria',
  INV_WEIGHT_CRITERIA: 'Invalid Horse Weight Criteria',
  INV_RIDER_NAME: 'Invalid Rider Name',
  INV_COURSE_NAME: 'Invalid Course Name',
  INV_RACE_NAME: 'Invalid Race Name',
  INV_PASS: 'Invalid password',
  INV_FIRST_NAME: 'Invalid First name',
  INV_MIDDLE_NAME: 'Invalid Middle name',
  INV_LAST_NAME: 'Invalid Last name',
  INV_PHONE_REGION: 'Invalid Phone Region',
  INV_PHONE_NUMBER: 'Invalid Phone Number',
  INV_COUNTRY: 'Invalid Country',
  INV_USER_EMAIL: 'Invalid Email id or Password',
  INV_OLD_PASS: 'Invalid Old Password',
  INV_NEW_PASS: 'New password and Old Passwords are same. Enter a unique password',
  USER_EXISTS: 'User with this email already exists',
  INV_USER_PARTICIPATED: 'You are already participated in this race',
  INV_REQ: 'Invalid reset request, the link is expired',
  QUERY_ERR: 'Error in executing query',
  DATA_ERR: 'No data is passed in req.body Object',
};
