export const POST_HORSE_REQUEST = "POST_HORSE_REQUEST";
export const POST_HORSE_SUCCESS = "POST_HORSE_SUCCESS";
export const POST_HORSE_FAILURE = "POST_HORSE_FAILURE";

export const GET_HORSE_REQUEST = "GET_HORSE_REQUEST";
export const GET_HORSE_SUCCESS = "GET_HORSE_SUCCESS";
export const GET_HORSE_FAILURE = "GET_HORSE_FAILURE";

export const GET_HORSE_REQUEST_BY_ID = "GET_HORSE_REQUEST_BY_ID";
export const GET_HORSE_SUCCESS_BY_ID = "GET_HORSE_SUCCESS_BY_ID";
export const GET_HORSE_FAILURE_BY_ID = "GET_HORSE_FAILURE_BY_ID";

export const UPDATE_HORSE_REQUEST = "UPDATE_HORSE_REQUEST";
export const UPDATE_HORSE_SUCCESS = "UPDATE_HORSE_SUCCESS";
export const UPDATE_HORSE_FAILURE = "UPDATE_HORSE_FAILURE";

export const DELETE_HORSE_REQUEST = "DELETE_HORSE_REQUEST";
export const DELETE_HORSE_SUCCESS = "DELETE_HORSE_SUCCESS";
export const DELETE_HORSE_FAILURE = "DELETE_HORSE_FAILURE";

export const GET_HORSE_GENDER = "GET_HORSE_GENDER";
export const GET_HORSE_COLOR = "GET_HORSE_COLOR";
export const GET_HORSE_DISCIPLINES = "GET_HORSE_DISCIPLINES";
export const GET_HORSE_BREED = "GET_HORSE_BREED";