export const POST_CONTACT_REQUEST = "POST_CONTACT_REQUEST";
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
export const POST_CONTACT_FAILURE = "POST_CONTACT_FAILURE";

export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE";

export const GET_CONTACT_REQUEST_BY_ID = "GET_CONTACT_REQUEST_BY_ID";
export const GET_CONTACT_SUCCESS_BY_ID = "GET_CONTACT_SUCCESS_BY_ID";
export const GET_CONTACT_FAILURE_BY_ID = "GET_CONTACT_FAILURE_BY_ID";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";
