export const CLIENT_SET = "CLIENT_SET";
export const CLIENT_UNSET = "CLIENT_UNSET";
export const SET_TOKEN = "SET_TOKEN";
export const SET_PAGEFLAG = "SET_PAGEFLAG";
export const UNSET_PAGEFLAG = "UNSET_PAGEFLAG";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
//--------------------

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const GET_USER_REQUEST_BY_ID = "GET_USER_REQUEST_BY_ID";
export const GET_USER_SUCCESS_BY_ID = "GET_USER_SUCCESS_BY_ID";
export const GET_USER_FAILURE_BY_ID = "GET_USER_FAILURE_BY_ID";

//---------------------------
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_HORSE = "GET_HORSE";
